### ISSUE TITLE
tar.gz support

### ISSUE THREAD

**Issue by vicaraya** [awslabs/amazon-s3-tar-tool#22]
Hello, I'd like to use this tool to extract certain folders in a `.tar.gz` file in s3. This is what I am facing

```
parallels@ubuntu-linux-22-04-02-desktop:~/amazon-s3-tar-tool/bin$ ./s3tar-linux-arm64 --region us-east-1 -xvf s3://test/test1/test1.tar.gz -C s3://anotherbucket/ folder/subfolder
2024/02/23 08:59:56 unable to parse CSV TOC from TAR
```

Is there any workaround I can do?

**Comment by yanko7** [comment]
Hello @vicaraya it looks like your tar is using gz compression, based on the extension (`tar.gz`). The tool today doesn't support compression, as that would require to download the tar.gz and uncompress it. The purpose of s3tar is to extract the data without downloading it. Regular tarballs without compression are simply a concatenation of the files, this allows us to Copy the data to another Amazon S3 location.
